[service.home1]
hierarchy = "/org/freedesktop/home1"
id = "org.freedesktop.home1"
module = "home1"
[[service.home1.overrides]]
interface = "org.freedesktop.home1.Manager"
todo_methods = ["ListHomes"]
todo_properties = ["AutoLogin"]
[[service.home1.overrides]]
interface = "org.freedesktop.home1.Home"
todo_properties = ["UnixRecord", "UserRecord"]

[service.hostname1]
default_object = "Hostnamed"
hierarchy = "/org/freedesktop/hostname1"
id = "org.freedesktop.hostname1"
module = "hostname1"

[service.import1]
hierarchy = "/org/freedesktop/import1"
id = "org.freedesktop.import1"
module = "import1"
[[service.import1.overrides]]
interface = "org.freedesktop.import1.Manager"
todo_methods = ["ListTransfers"]
[[service.import1.overrides]]
interface = "org.freedesktop.import1.Transfer"
todo_properties = ["Type"]

[service.locale1]
default_object = "Localed"
hierarchy = "/org/freedesktop/locale1"
id = "org.freedesktop.locale1"
module = "locale1"

[service.login1]
hierarchy = "/org/freedesktop/login1"
id = "org.freedesktop.login1"
module = "login1"
[[service.login1.overrides]]
interface = "org.freedesktop.login1.Manager"
todo_methods = ["ListSessions", "ListUsers", "ListSeats", "ListInhibitors"]
todo_properties = [
    "EnableWallMessages",
    "ScheduledShutdown",
    "Sessions",
    "WallMessage",
]
[[service.login1.overrides]]
interface = "org.freedesktop.login1.Seat"
todo_properties = ["ActiveSession", "Sessions"]
[[service.login1.overrides]]
interface = "org.freedesktop.login1.User"
todo_properties = ["Display", "Sessions"]
[[service.login1.overrides]]
interface = "org.freedesktop.login1.Session"
todo_properties = ["Display", "Seat", "Type", "User"]

[service.machine1]
hierarchy = "/org/freedesktop/machine1"
id = "org.freedesktop.machine1"
module = "machine1"
[[service.machine1.overrides]]
interface = "org.freedesktop.machine1.Machine"
todo_methods = ["GetAddresses", "GetOSRelease"]
[[service.machine1.overrides]]
interface = "org.freedesktop.machine1.Manager"
todo_methods = [
    "ListMachines",
    "ListImages",
    "GetMachineAddresses",
    "GetMachineOSRelease",
    "GetImageMachineInfo",
    "GetImageOSRelease",
]

[service.oom1]
hierarchy = "/org/freedesktop/oom1"
id = "org.freedesktop.oom1"
module = "oom1"

[service.portable1]
hierarchy = "/org/freedesktop/portable1"
id = "org.freedesktop.portable1"
module = "portable1"
[[service.portable1.overrides]]
interface = "org.freedesktop.portable1.Manager"
todo_methods = [
    "ListImages",
    "GetImageOSRelease",
    "GetImageMetadata",
    "GetImageMetadataWithExtensions",
]
[[service.portable1.overrides]]
interface = "org.freedesktop.portable1.Image"
todo_methods = ["GetOSRelease", "GetMetadata", "GetMetadataWithExtensions"]
todo_properties = ["Type"]


[service.resolve1]
hierarchy = "/org/freedesktop/resolve1"
id = "org.freedesktop.resolve1"
module = "resolve1"
[[service.resolve1.overrides]]
interface = "org.freedesktop.resolve1.Manager"
todo_methods = [
    "ResolveHostname",
    "ResolveAddress",
    "ResolveRecord",
    "ResolveService",
    "SetLinkDNS",
    "SetLinkDNSEx",
    "RegisterService",
]
todo_properties = [
    "FallbackDNS",
    "FallbackDNSEx",
    "Domains",
    "TransactionStatistics",
    "CacheStatistics",
    "DNSSECStatistics",
    "DNS",
    "DNSEx",
    "CurrentDNSServer",
    "CurrentDNSServerEx",
]
[[service.resolve1.overrides]]
interface = "org.freedesktop.resolve1.Link"
todo_methods = ["SetDNS", "SetDNSEx"]
todo_properties = ["DNS", "DNSEx", "CurrentDNSServer", "CurrentDNSServerEx"]

[service.systemd1]
hierarchy = "/org/freedesktop/systemd1"
id = "org.freedesktop.systemd1"
module = "systemd1"
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Manager"
todo_methods = [
    "EnqueueUnitJob",
    "StartTransientUnit",
    "GetJobAfter",
    "GetJobBefore",
    "ListUnits",
    "ListUnitsFiltered",
    "ListUnitsByPatterns",
    "ListUnitsByNames",
    "ListJobs",
    "GetDynamicUsers",
]
todo_properties = [
    "LogLevel",
    "LogTarget",
    "RuntimeWatchdogUSec",
    "RebootWatchdogUSec",
    "KExecWatchdogUSec",
    "ServiceWatchdogs",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Unit"
todo_methods = ["EnqueueJob"]
todo_properties = ["Job", "Conditions", "Asserts", "LoadError"]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Service"
todo_properties = [
    "RestartPreventExitStatus",
    "RestartForceExitStatus",
    "SuccessExitStatus",
    "ExecCondition",
    "ExecConditionEx",
    "ExecStartPre",
    "ExecStartPreEx",
    "ExecStart",
    "ExecStartEx",
    "ExecStartPost",
    "ExecStartPostEx",
    "ExecReload",
    "ExecReloadEx",
    "ExecStop",
    "ExecStopEx",
    "ExecStopPost",
    "ExecStopPostEx",
    "IPAddressAllow",
    "IPAddressDeny",
    "SocketBindAllow",
    "SocketBindDeny",
    "ExtensionImages",
    "MountImages",
    "LogExtraFields",
    "SetCredential",
    "SELinuxContext",
    "AppArmorProfile",
    "SmackProcessLabel",
    "SystemCallFilter",
    "SystemCallLog",
    "RestrictAddressFamilies",
    "BindPaths",
    "BindReadOnlyPaths",
    "Type",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Socket"
todo_properties = [
    "ExecStartPre",
    "ExecStartPost",
    "ExecStopPre",
    "ExecStopPost",
    "IPAddressAllow",
    "IPAddressDeny",
    "SocketBindAllow",
    "SocketBindDeny",
    "ExtensionImages",
    "MountImages",
    "LogExtraFields",
    "SetCredential",
    "SELinuxContext",
    "AppArmorProfile",
    "SmackProcessLabel",
    "SystemCallFilter",
    "SystemCallLog",
    "RestrictAddressFamilies",
    "BindPaths",
    "BindReadOnlyPaths",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Automount"
todo_properties = ["Where"]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Mount"
todo_properties = [
    "ExecMount",
    "ExecUnmount",
    "ExecRemount",
    "IPAddressAllow",
    "IPAddressDeny",
    "SocketBindAllow",
    "SocketBindDeny",
    "ExtensionImages",
    "MountImages",
    "LogExtraFields",
    "SetCredential",
    "SELinuxContext",
    "AppArmorProfile",
    "SmackProcessLabel",
    "SystemCallFilter",
    "SystemCallLog",
    "RestrictAddressFamilies",
    "BindPaths",
    "BindReadOnlyPaths",
    "Where",
    "Type",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Timer"
todo_properties = ["TimersMonotonic", "TimersCalendar"]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Swap"
todo_properties = [
    "AppArmorProfile",
    "BindPaths",
    "BindReadOnlyPaths",
    "ExecActivate",
    "ExecDeactivate",
    "ExtensionImages",
    "IPAddressAllow",
    "IPAddressDeny",
    "LogExtraFields",
    "MountImages",
    "RestrictAddressFamilies",
    "SELinuxContext",
    "SetCredential",
    "SmackProcessLabel",
    "SocketBindAllow",
    "SocketBindDeny",
    "SystemCallFilter",
    "SystemCallLog",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Slice"
todo_properties = [
    "IPAddressAllow",
    "IPAddressDeny",
    "SocketBindAllow",
    "SocketBindDeny",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Scope"
todo_properties = [
    "IPAddressAllow",
    "IPAddressDeny",
    "SocketBindAllow",
    "SocketBindDeny",
]
[[service.systemd1.overrides]]
interface = "org.freedesktop.systemd1.Job"
todo_methods = ["GetAfter", "GetBefore"]

[service.timedate1]
default_object = "Timedated"
hierarchy = "/org/freedesktop/timedate1"
id = "org.freedesktop.timedate1"
module = "timedate1"
